apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: CapstoneEKS
  region: us-west-2

vpc:
  subnets:
    public:
      us-west-2a: { id: subnet-0ff156e0c4a6d300c }
      us-west-2b: { id: subnet-0549cdab573695c03 }
      us-west-2c: { id: subnet-0426fb4a607393184 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.small
    desiredCapacity: 10
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: m5.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true